// console.log(2+2);
// console.log(2-2);
// console.log(2*2);
// console.log(2/2);
// console.log(2%3);
// console.log("1"+2+3);
// console.log("1"+2+"3");
// console.log(1+2+"3");
// console.log(1+"2"+"3");
let a=1;
// b=++a+ ++a + ++a + ++a;
b=a++ + a++ + a++ + a++;
console.log((`a:${a}, b:${b}`));
